/* DO NOT EDIT! This is an autogenerated file. */

Storage::Storage()
{
    buildings.name = "Building";
    clanMechanoids.name = "ClanMechanoid";
    clanReputations.name = "ClanReputation";
    clans.name = "Clan";
    configurationEquipments.name = "ConfigurationEquipment";
    configurationGoods.name = "ConfigurationGood";
    configurationProjectiles.name = "ConfigurationProjectile";
    configurationWeapons.name = "ConfigurationWeapon";
    configurations.name = "Configuration";
    equipments.name = "Equipment";
    gliders.name = "Glider";
    goods.name = "Good";
    groupMechanoids.name = "GroupMechanoid";
    groups.name = "Group";
    mapBuildingEquipments.name = "MapBuildingEquipment";
    mapBuildingGliders.name = "MapBuildingGlider";
    mapBuildingGoods.name = "MapBuildingGood";
    mapBuildingModificators.name = "MapBuildingModificator";
    mapBuildingProjectiles.name = "MapBuildingProjectile";
    mapBuildingWeapons.name = "MapBuildingWeapon";
    mapBuildings.name = "MapBuilding";
    mapGoods.name = "MapGood";
    mapObjects.name = "MapObject";
    maps.name = "Map";
    mechanoidQuests.name = "MechanoidQuest";
    mechanoids.name = "Mechanoid";
    modificationClans.name = "ModificationClan";
    modificationMaps.name = "ModificationMap";
    modificationMechanoids.name = "ModificationMechanoid";
    modifications.name = "Modification";
    modificators.name = "Modificator";
    objects.name = "Object";
    players.name = "Player";
    projectiles.name = "Projectile";
    questRewardEquipments.name = "QuestRewardEquipment";
    questRewardGliders.name = "QuestRewardGlider";
    questRewardGoods.name = "QuestRewardGood";
    questRewardModificators.name = "QuestRewardModificator";
    questRewardProjectiles.name = "QuestRewardProjectile";
    questRewardReputations.name = "QuestRewardReputation";
    questRewardWeapons.name = "QuestRewardWeapon";
    questRewards.name = "QuestReward";
    quests.name = "Quest";
    scriptVariables.name = "ScriptVariable";
    settings.name = "Setting";
    strings.name = "String";
    tables.name = "Table";
    weapons.name = "Weapon";
}

Storage::~Storage()
{
}
