/* DO NOT EDIT! This is an autogenerated file. */

EObjectType getTableType(const std::string &table);
std::string getTableNameByType(EObjectType type);
#ifdef USE_QT
void retranslateFieldNames();
QString getFieldName(const std::string &name);
#endif
