/* DO NOT EDIT! This is an autogenerated file. */

#pragma once

namespace polygon4
{

namespace detail
{

enum class EObjectType : int
{
    None,

    Building,
    ClanMechanoid,
    ClanReputation,
    Clan,
    ConfigurationEquipment,
    ConfigurationGood,
    ConfigurationProjectile,
    ConfigurationWeapon,
    Configuration,
    Equipment,
    Glider,
    Good,
    GroupMechanoid,
    Group,
    MapBuildingEquipment,
    MapBuildingGlider,
    MapBuildingGood,
    MapBuildingModificator,
    MapBuildingProjectile,
    MapBuildingWeapon,
    MapBuilding,
    MapGood,
    MapObject,
    Map,
    MechanoidQuest,
    Mechanoid,
    ModificationClan,
    ModificationMap,
    ModificationMechanoid,
    Modification,
    Modificator,
    Object,
    Player,
    Projectile,
    QuestRewardEquipment,
    QuestRewardGlider,
    QuestRewardGood,
    QuestRewardModificator,
    QuestRewardProjectile,
    QuestRewardReputation,
    QuestRewardWeapon,
    QuestReward,
    Quest,
    ScriptVariable,
    Setting,
    String,
    Table,
    Weapon,

    Any,
};

} // namespace detail

} // namespace polygon4
