/* DO NOT EDIT! This is an autogenerated file. */

class Storage
{
public:
    CMap<Ptr<Building>> buildings;
    CVector<Ptr<ClanReputation>> clanReputations;
    CMap<Ptr<Clan>> clans;
    CVector<Ptr<ConfigurationEquipment>> configurationEquipments;
    CVector<Ptr<ConfigurationGood>> configurationGoods;
    CVector<Ptr<ConfigurationProjectile>> configurationProjectiles;
    CVector<Ptr<ConfigurationWeapon>> configurationWeapons;
    CMap<Ptr<Configuration>> configurations;
    CMap<Ptr<Coordinate>> coordinates;
    CMap<Ptr<Equipment>> equipments;
    CMap<Ptr<Glider>> gliders;
    CMap<Ptr<Good>> goods;
    CVector<Ptr<MapBuildingEquipment>> mapBuildingEquipments;
    CVector<Ptr<MapBuildingGlider>> mapBuildingGliders;
    CVector<Ptr<MapBuildingGood>> mapBuildingGoods;
    CVector<Ptr<MapBuildingModificator>> mapBuildingModificators;
    CVector<Ptr<MapBuildingProjectile>> mapBuildingProjectiles;
    CVector<Ptr<MapBuildingWeapon>> mapBuildingWeapons;
    CMap<Ptr<MapBuilding>> mapBuildings;
    CMap<Ptr<MapObject>> mapObjects;
    CMap<Ptr<Map>> maps;
    CMap<Ptr<MechanoidGroup>> mechanoidGroups;
    CMap<Ptr<Mechanoid>> mechanoids;
    CVector<Ptr<ModificationClan>> modificationClans;
    CVector<Ptr<ModificationMap>> modificationMaps;
    CVector<Ptr<ModificationMechanoid>> modificationMechanoids;
    CMap<Ptr<Modification>> modifications;
    CMap<Ptr<Modificator>> modificators;
    CMap<Ptr<Object>> objects;
    CMap<Ptr<Player>> players;
    CMap<Ptr<Projectile>> projectiles;
    CVector<Ptr<QuestRewardEquipment>> questRewardEquipments;
    CVector<Ptr<QuestRewardGlider>> questRewardGliders;
    CVector<Ptr<QuestRewardGood>> questRewardGoods;
    CVector<Ptr<QuestRewardModificator>> questRewardModificators;
    CVector<Ptr<QuestRewardProjectile>> questRewardProjectiles;
    CVector<Ptr<QuestRewardReputation>> questRewardReputations;
    CVector<Ptr<QuestRewardWeapon>> questRewardWeapons;
    CMap<Ptr<QuestReward>> questRewards;
    CMap<Ptr<Quest>> quests;
    CVector<Ptr<SaveObject>> saveObjects;
    CVector<Ptr<SavePlayer>> savePlayers;
    CVector<Ptr<SaveQuest>> saveQuests;
    CMap<Ptr<Save>> saves;
    CVector<Ptr<ScriptVariable>> scriptVariables;
    CMap<Ptr<String>> strings;
    CMap<Ptr<Weapon>> weapons;

    virtual void clear() = 0;
    virtual void load(ProgressCallback callback = ProgressCallback()) = 0;
    virtual void save(ProgressCallback callback = ProgressCallback()) = 0;

#ifdef USE_QT
    virtual void printQtTreeView(QTreeWidgetItem *root) const = 0;
    virtual QTreeWidgetItem *addRecord(QTreeWidgetItem *item) = 0;
    virtual void deleteRecord(QTreeWidgetItem *item) = 0;
#endif

    virtual OrderedObjectMap getOrderedMap(EObjectType type) const = 0;
};

