/* DO NOT EDIT! This is an autogenerated file. */

struct Building;
struct ClanReputation;
struct Clan;
struct ConfigurationEquipment;
struct ConfigurationGood;
struct ConfigurationProjectile;
struct ConfigurationWeapon;
struct Configuration;
struct Coordinate;
struct Equipment;
struct Glider;
struct Good;
struct MapBuildingEquipment;
struct MapBuildingGlider;
struct MapBuildingGood;
struct MapBuildingModificator;
struct MapBuildingProjectile;
struct MapBuildingWeapon;
struct MapBuilding;
struct MapObject;
struct Map;
struct MechanoidGroup;
struct Mechanoid;
struct ModificationClan;
struct ModificationMap;
struct ModificationMechanoid;
struct Modification;
struct Modificator;
struct Object;
struct Player;
struct Projectile;
struct QuestRewardEquipment;
struct QuestRewardGlider;
struct QuestRewardGood;
struct QuestRewardModificator;
struct QuestRewardProjectile;
struct QuestRewardReputation;
struct QuestRewardWeapon;
struct QuestReward;
struct Quest;
struct SaveObject;
struct SavePlayer;
struct SaveQuest;
struct Save;
struct ScriptVariable;
struct String;
struct Weapon;

struct Building
{
    int id = 0;
    Text text_id;
    Text resource;
    IdPtr<String> name;
};

struct ClanReputation
{
    IdPtr<Clan> clan;
    IdPtr<Clan> clan2;
    float reputation = 0.0f;
};

struct Clan
{
    int id = 0;
    Text text_id;
    Text resource;
    IdPtr<String> name;

    CVector<Ptr<ClanReputation>> reputations;
};

struct ConfigurationEquipment
{
    IdPtr<Configuration> configuration;
    IdPtr<Equipment> equipment;
    int quantity = 0;
};

struct ConfigurationGood
{
    IdPtr<Configuration> configuration;
    IdPtr<Good> goods;
    int quantity = 0;
};

struct ConfigurationProjectile
{
    IdPtr<Configuration> configuration;
    IdPtr<Projectile> projectile;
    int quantity = 0;
};

struct ConfigurationWeapon
{
    IdPtr<Configuration> configuration;
    IdPtr<Weapon> weapon;
    int quantity = 0;
};

struct Configuration
{
    int id = 0;
    Text text_id;
    IdPtr<String> name;
    IdPtr<Glider> glider;

    CVector<Ptr<ConfigurationEquipment>> equipments;
    CVector<Ptr<ConfigurationGood>> goods;
    CVector<Ptr<ConfigurationProjectile>> projectiles;
    CVector<Ptr<ConfigurationWeapon>> weapons;
};

struct Coordinate
{
    int id = 0;
    float x = 0.0f;
    float y = 0.0f;
    float z = 0.0f;
    float yaw = 0.0f;
    float pitch = 0.0f;
    float roll = 0.0f;
};

struct Equipment
{
    int id = 0;
    Text text_id;
    Text resource;
    IdPtr<String> name;
    int type = 0;
    int standard = 0;
    float weight = 0.0f;
    float durability = 0.0f;
    float power = 0.0f;
    float value1 = 0.0f;
    float value2 = 0.0f;
    float value3 = 0.0f;
    int manual = 0;
    float price = 0.0f;
    int notrade = 0;
};

struct Glider
{
    int id = 0;
    Text text_id;
    Text resource;
    IdPtr<String> name;
    int standard = 0;
    float weight = 0.0f;
    float maxweight = 0.0f;
    float rotatespeed = 0.0f;
    float armor = 0.0f;
    int price = 0;
    float restore = 0.0f;
    float power = 0.0f;
    int special = 0;
};

struct Good
{
    int id = 0;
    Text text_id;
    Text resource;
    IdPtr<String> name;
    int price = 0;
    int notrade = 0;
    float weight = 0.0f;
};

struct MapBuildingEquipment
{
    IdPtr<MapBuilding> mapBuilding;
    IdPtr<Equipment> equipment;
    int quantity = 0;
};

struct MapBuildingGlider
{
    IdPtr<MapBuilding> mapBuilding;
    IdPtr<Glider> glider;
    int quantity = 0;
};

struct MapBuildingGood
{
    IdPtr<MapBuilding> mapBuilding;
    IdPtr<Good> goods;
    int quantity = 0;
};

struct MapBuildingModificator
{
    IdPtr<MapBuilding> mapBuilding;
    IdPtr<Modificator> modificator;
    int quantity = 0;
};

struct MapBuildingProjectile
{
    IdPtr<MapBuilding> mapBuilding;
    IdPtr<Projectile> projectile;
    int quantity = 0;
};

struct MapBuildingWeapon
{
    IdPtr<MapBuilding> mapBuilding;
    IdPtr<Weapon> weapon;
    int quantity = 0;
};

struct MapBuilding
{
    int id = 0;
    Text text_id;
    IdPtr<Map> map;
    IdPtr<Building> building;
    IdPtr<Coordinate> coordinate;

    CVector<Ptr<MapBuildingEquipment>> equipments;
    CVector<Ptr<MapBuildingGlider>> gliders;
    CVector<Ptr<MapBuildingGood>> goods;
    CVector<Ptr<MapBuildingModificator>> modificators;
    CVector<Ptr<MapBuildingProjectile>> projectiles;
    CVector<Ptr<MapBuildingWeapon>> weapons;
};

struct MapObject
{
    int id = 0;
    IdPtr<Map> map;
    IdPtr<Object> object;
    IdPtr<Coordinate> coordinate;
};

struct Map
{
    int id = 0;
    Text text_id;
    Text resource;
    IdPtr<String> name;
};

struct MechanoidGroup
{
    int id = 0;
    Text text_id;
    IdPtr<String> name;
};

struct Mechanoid
{
    int id = 0;
    Text text_id;
    Text name;
    int generation = 0;
    float rating = 0.0f;
    float money = 0.0f;
    IdPtr<Configuration> configuration;
    IdPtr<Clan> clan;
    IdPtr<MechanoidGroup> group;
    float rating_fight = 0.0f;
    float rating_courier = 0.0f;
    float rating_trade = 0.0f;
    IdPtr<Map> map;
    IdPtr<MapBuilding> map_building;
    IdPtr<Coordinate> coordinate;
};

struct ModificationClan
{
    IdPtr<Modification> modification;
    IdPtr<Clan> clan;
};

struct ModificationMap
{
    IdPtr<Modification> modification;
    IdPtr<Map> map;
};

struct ModificationMechanoid
{
    IdPtr<Modification> modification;
    IdPtr<Mechanoid> mechanoid;
};

struct Modification
{
    int id = 0;
    Text text_id;
    Text name;
    Text author;
    int date_created = 0;
    int date_modified = 0;
    Text comment;
    float version = 0.0f;
    Text script_language;
    Text script_main;

    CVector<Ptr<ModificationClan>> clans;
    CVector<Ptr<ModificationMap>> maps;
    CVector<Ptr<ModificationMechanoid>> mechanoids;
};

struct Modificator
{
    int id = 0;
    Text text_id;
    Text resource;
    Text name;
    float probability = 0.0f;
    float price = 0.0f;
    float k_price = 0.0f;
    float k_param1 = 0.0f;
    float k_param2 = 0.0f;
};

struct Object
{
    int id = 0;
    Text text_id;
    Text resource;
    Text name;
    int type = 0;
};

struct Player
{
    int id = 0;
    IdPtr<Mechanoid> mechaniod;
};

struct Projectile
{
    int id = 0;
    Text text_id;
    Text resource;
    IdPtr<String> name;
    int type = 0;
    float weight = 0.0f;
    float damage = 0.0f;
    float speed = 0.0f;
    float scale = 0.0f;
    int notrade = 0;
};

struct QuestRewardEquipment
{
    IdPtr<QuestReward> questReward;
    IdPtr<Equipment> equipment;
    int quantity = 0;
};

struct QuestRewardGlider
{
    IdPtr<QuestReward> questReward;
    IdPtr<Glider> glider;
    int quantity = 0;
};

struct QuestRewardGood
{
    IdPtr<QuestReward> questReward;
    IdPtr<Good> good;
    int quantity = 0;
};

struct QuestRewardModificator
{
    IdPtr<QuestReward> questReward;
    IdPtr<Modificator> modificator;
    int quantity = 0;
};

struct QuestRewardProjectile
{
    IdPtr<QuestReward> questReward;
    IdPtr<Projectile> projectile;
    int quantity = 0;
};

struct QuestRewardReputation
{
    IdPtr<QuestReward> questReward;
    IdPtr<Clan> clan;
    float reputation = 0.0f;
};

struct QuestRewardWeapon
{
    IdPtr<QuestReward> questReward;
    IdPtr<Weapon> weapon;
    int quantity = 0;
};

struct QuestReward
{
    int id = 0;
    int money = 0;
    float rating = 0.0f;

    CVector<Ptr<QuestRewardEquipment>> equipments;
    CVector<Ptr<QuestRewardGlider>> gliders;
    CVector<Ptr<QuestRewardGood>> goods;
    CVector<Ptr<QuestRewardModificator>> modificators;
    CVector<Ptr<QuestRewardProjectile>> projectiles;
    CVector<Ptr<QuestRewardReputation>> reputations;
    CVector<Ptr<QuestRewardWeapon>> weapons;
};

struct Quest
{
    int id = 0;
    Text text_id;
    IdPtr<String> name;
    IdPtr<String> title;
    IdPtr<String> description;
    IdPtr<QuestReward> reward;
    int time = 0;
};

struct SaveObject
{
    IdPtr<Save> save;
    IdPtr<Object> object;
    IdPtr<Map> map;
    IdPtr<Coordinate> coordinate;
};

struct SavePlayer
{
    IdPtr<Save> save;
    IdPtr<Player> player;
};

struct SaveQuest
{
    IdPtr<Save> save;
    IdPtr<Quest> quest;
    int state = 0;
};

struct Save
{
    int id = 0;
    IdPtr<Modification> modification;
    Text name;
    int date = 0;

    CVector<Ptr<SaveObject>> objects;
    CVector<Ptr<SavePlayer>> players;
    CVector<Ptr<SaveQuest>> quests;

    CVector<Ptr<ScriptVariable>> scriptVariables;
};

struct ScriptVariable
{
    IdPtr<Save> save;
    Text variable;
    Text value;
};

enum class LocalizationType : EnumType
{
    ru,
    en,

    max
};

struct String
{
    int id = 0;
    Text ru;
    Text en;

    Text get(int loc_id = 0) const { return ((Text *)&ru)[loc_id]; }
};

struct Weapon
{
    int id = 0;
    Text text_id;
    Text resource;
    IdPtr<String> name;
    int type = 0;
    int standard = 0;
    float weight = 0.0f;
    float power = 0.0f;
    float firerate = 0.0f;
    float damage = 0.0f;
    float price = 0.0f;
    IdPtr<Projectile> projectile;
};

