/* DO NOT EDIT! This is an autogenerated file. */

#pragma once

DLL_EXPORT EObjectType getTableType(const std::string &table);
DLL_EXPORT Text getTableNameByType(EObjectType type);

#ifdef USE_QT
void retranslateFieldNames();
QString getFieldName(const std::string &name);
void retranslateTableNames();
QString getTableName(const std::string &name);
#endif
