/* DO NOT EDIT! This is an autogenerated file. */

#pragma once

namespace polygon4
{

namespace detail
{

enum class EObjectType : EnumType
{
    None,
    Building,
    Clan,
    ClanReputation,
    Configuration,
    ConfigurationEquipment,
    ConfigurationGood,
    ConfigurationProjectile,
    ConfigurationWeapon,
    Equipment,
    Glider,
    Good,
    Group,
    GroupMechanoid,
    Map,
    MapBuilding,
    MapBuildingEquipment,
    MapBuildingGlider,
    MapBuildingGood,
    MapBuildingModificator,
    MapBuildingProjectile,
    MapBuildingWeapon,
    MapGood,
    MapObject,
    Mechanoid,
    MechanoidQuest,
    Modification,
    ModificationMap,
    Modificator,
    Object,
    Player,
    Projectile,
    Quest,
    QuestReward,
    QuestRewardEquipment,
    QuestRewardGlider,
    QuestRewardGood,
    QuestRewardModificator,
    QuestRewardProjectile,
    QuestRewardReputation,
    QuestRewardWeapon,
    ScriptVariable,
    Setting,
    String,
    Table,
    Weapon,
    Any,
};

} // namespace detail

} // namespace polygon4
