/* DO NOT EDIT! This is an autogenerated file. */

#pragma once

class StorageImpl : public Storage
{
#ifdef USE_QT
    Q_DECLARE_TR_FUNCTIONS(StorageImpl)
#endif

private:
    std::shared_ptr<Database> db;

private:
    void _loadBuildings();
    void _loadBuildingsPtrs();
    void _loadBuildingsArrays();
    void _saveBuildings() const;

    void _loadClans();
    void _loadClansPtrs();
    void _loadClansArrays();
    void _saveClans() const;

    void _loadClanReputations();
    void _loadClanReputationsPtrs();
    void _loadClanReputationsArrays();
    void _saveClanReputations() const;

    void _loadConfigurations();
    void _loadConfigurationsPtrs();
    void _loadConfigurationsArrays();
    void _saveConfigurations() const;

    void _loadConfigurationEquipments();
    void _loadConfigurationEquipmentsPtrs();
    void _loadConfigurationEquipmentsArrays();
    void _saveConfigurationEquipments() const;

    void _loadConfigurationGoods();
    void _loadConfigurationGoodsPtrs();
    void _loadConfigurationGoodsArrays();
    void _saveConfigurationGoods() const;

    void _loadConfigurationProjectiles();
    void _loadConfigurationProjectilesPtrs();
    void _loadConfigurationProjectilesArrays();
    void _saveConfigurationProjectiles() const;

    void _loadConfigurationWeapons();
    void _loadConfigurationWeaponsPtrs();
    void _loadConfigurationWeaponsArrays();
    void _saveConfigurationWeapons() const;

    void _loadEquipments();
    void _loadEquipmentsPtrs();
    void _loadEquipmentsArrays();
    void _saveEquipments() const;

    void _loadGliders();
    void _loadGlidersPtrs();
    void _loadGlidersArrays();
    void _saveGliders() const;

    void _loadGoods();
    void _loadGoodsPtrs();
    void _loadGoodsArrays();
    void _saveGoods() const;

    void _loadGroups();
    void _loadGroupsPtrs();
    void _loadGroupsArrays();
    void _saveGroups() const;

    void _loadGroupMechanoids();
    void _loadGroupMechanoidsPtrs();
    void _loadGroupMechanoidsArrays();
    void _saveGroupMechanoids() const;

    void _loadMaps();
    void _loadMapsPtrs();
    void _loadMapsArrays();
    void _saveMaps() const;

    void _loadMapBuildings();
    void _loadMapBuildingsPtrs();
    void _loadMapBuildingsArrays();
    void _saveMapBuildings() const;

    void _loadMapBuildingEquipments();
    void _loadMapBuildingEquipmentsPtrs();
    void _loadMapBuildingEquipmentsArrays();
    void _saveMapBuildingEquipments() const;

    void _loadMapBuildingGliders();
    void _loadMapBuildingGlidersPtrs();
    void _loadMapBuildingGlidersArrays();
    void _saveMapBuildingGliders() const;

    void _loadMapBuildingGoods();
    void _loadMapBuildingGoodsPtrs();
    void _loadMapBuildingGoodsArrays();
    void _saveMapBuildingGoods() const;

    void _loadMapBuildingModificators();
    void _loadMapBuildingModificatorsPtrs();
    void _loadMapBuildingModificatorsArrays();
    void _saveMapBuildingModificators() const;

    void _loadMapBuildingProjectiles();
    void _loadMapBuildingProjectilesPtrs();
    void _loadMapBuildingProjectilesArrays();
    void _saveMapBuildingProjectiles() const;

    void _loadMapBuildingWeapons();
    void _loadMapBuildingWeaponsPtrs();
    void _loadMapBuildingWeaponsArrays();
    void _saveMapBuildingWeapons() const;

    void _loadMapGoods();
    void _loadMapGoodsPtrs();
    void _loadMapGoodsArrays();
    void _saveMapGoods() const;

    void _loadMapObjects();
    void _loadMapObjectsPtrs();
    void _loadMapObjectsArrays();
    void _saveMapObjects() const;

    void _loadMechanoids();
    void _loadMechanoidsPtrs();
    void _loadMechanoidsArrays();
    void _saveMechanoids() const;

    void _loadMechanoidQuests();
    void _loadMechanoidQuestsPtrs();
    void _loadMechanoidQuestsArrays();
    void _saveMechanoidQuests() const;

    void _loadModifications();
    void _loadModificationsPtrs();
    void _loadModificationsArrays();
    void _saveModifications() const;

    void _loadModificationMaps();
    void _loadModificationMapsPtrs();
    void _loadModificationMapsArrays();
    void _saveModificationMaps() const;

    void _loadModificators();
    void _loadModificatorsPtrs();
    void _loadModificatorsArrays();
    void _saveModificators() const;

    void _loadObjects();
    void _loadObjectsPtrs();
    void _loadObjectsArrays();
    void _saveObjects() const;

    void _loadPlayers();
    void _loadPlayersPtrs();
    void _loadPlayersArrays();
    void _savePlayers() const;

    void _loadProjectiles();
    void _loadProjectilesPtrs();
    void _loadProjectilesArrays();
    void _saveProjectiles() const;

    void _loadQuests();
    void _loadQuestsPtrs();
    void _loadQuestsArrays();
    void _saveQuests() const;

    void _loadQuestRewards();
    void _loadQuestRewardsPtrs();
    void _loadQuestRewardsArrays();
    void _saveQuestRewards() const;

    void _loadQuestRewardEquipments();
    void _loadQuestRewardEquipmentsPtrs();
    void _loadQuestRewardEquipmentsArrays();
    void _saveQuestRewardEquipments() const;

    void _loadQuestRewardGliders();
    void _loadQuestRewardGlidersPtrs();
    void _loadQuestRewardGlidersArrays();
    void _saveQuestRewardGliders() const;

    void _loadQuestRewardGoods();
    void _loadQuestRewardGoodsPtrs();
    void _loadQuestRewardGoodsArrays();
    void _saveQuestRewardGoods() const;

    void _loadQuestRewardModificators();
    void _loadQuestRewardModificatorsPtrs();
    void _loadQuestRewardModificatorsArrays();
    void _saveQuestRewardModificators() const;

    void _loadQuestRewardProjectiles();
    void _loadQuestRewardProjectilesPtrs();
    void _loadQuestRewardProjectilesArrays();
    void _saveQuestRewardProjectiles() const;

    void _loadQuestRewardReputations();
    void _loadQuestRewardReputationsPtrs();
    void _loadQuestRewardReputationsArrays();
    void _saveQuestRewardReputations() const;

    void _loadQuestRewardWeapons();
    void _loadQuestRewardWeaponsPtrs();
    void _loadQuestRewardWeaponsArrays();
    void _saveQuestRewardWeapons() const;

    void _loadScriptVariables();
    void _loadScriptVariablesPtrs();
    void _loadScriptVariablesArrays();
    void _saveScriptVariables() const;

    void _loadSettings();
    void _loadSettingsPtrs();
    void _loadSettingsArrays();
    void _saveSettings() const;

    void _loadStrings();
    void _loadStringsPtrs();
    void _loadStringsArrays();
    void _saveStrings() const;

    void _loadTables();
    void _loadTablesPtrs();
    void _loadTablesArrays();
    void _saveTables() const;

    void _loadWeapons();
    void _loadWeaponsPtrs();
    void _loadWeaponsArrays();
    void _saveWeapons() const;

public:
    StorageImpl(std::shared_ptr<Database> db) : db(db) {}

    void setDb(std::shared_ptr<Database> db) { this->db = db; }

    virtual void create() const override;
    virtual void clear() override;
    virtual void load(ProgressCallback callback = ProgressCallback()) override;
    virtual void save(ProgressCallback callback = ProgressCallback()) const override;

    virtual Ptr<Building> addBuilding() override;
    virtual void deleteBuilding(IObjectBase *object) override;
    virtual Ptr<Clan> addClan() override;
    virtual void deleteClan(IObjectBase *object) override;
    virtual Ptr<ClanReputation> addClanReputation(IObjectBase *parent = nullptr) override;
    virtual void deleteClanReputation(IObjectBase *object) override;
    virtual Ptr<Configuration> addConfiguration() override;
    virtual void deleteConfiguration(IObjectBase *object) override;
    virtual Ptr<ConfigurationEquipment> addConfigurationEquipment(IObjectBase *parent = nullptr) override;
    virtual void deleteConfigurationEquipment(IObjectBase *object) override;
    virtual Ptr<ConfigurationGood> addConfigurationGood(IObjectBase *parent = nullptr) override;
    virtual void deleteConfigurationGood(IObjectBase *object) override;
    virtual Ptr<ConfigurationProjectile> addConfigurationProjectile(IObjectBase *parent = nullptr) override;
    virtual void deleteConfigurationProjectile(IObjectBase *object) override;
    virtual Ptr<ConfigurationWeapon> addConfigurationWeapon(IObjectBase *parent = nullptr) override;
    virtual void deleteConfigurationWeapon(IObjectBase *object) override;
    virtual Ptr<Equipment> addEquipment() override;
    virtual void deleteEquipment(IObjectBase *object) override;
    virtual Ptr<Glider> addGlider() override;
    virtual void deleteGlider(IObjectBase *object) override;
    virtual Ptr<Good> addGood() override;
    virtual void deleteGood(IObjectBase *object) override;
    virtual Ptr<Group> addGroup() override;
    virtual void deleteGroup(IObjectBase *object) override;
    virtual Ptr<GroupMechanoid> addGroupMechanoid(IObjectBase *parent = nullptr) override;
    virtual void deleteGroupMechanoid(IObjectBase *object) override;
    virtual Ptr<Map> addMap() override;
    virtual void deleteMap(IObjectBase *object) override;
    virtual Ptr<MapBuilding> addMapBuilding(IObjectBase *parent = nullptr) override;
    virtual void deleteMapBuilding(IObjectBase *object) override;
    virtual Ptr<MapBuildingEquipment> addMapBuildingEquipment(IObjectBase *parent = nullptr) override;
    virtual void deleteMapBuildingEquipment(IObjectBase *object) override;
    virtual Ptr<MapBuildingGlider> addMapBuildingGlider(IObjectBase *parent = nullptr) override;
    virtual void deleteMapBuildingGlider(IObjectBase *object) override;
    virtual Ptr<MapBuildingGood> addMapBuildingGood(IObjectBase *parent = nullptr) override;
    virtual void deleteMapBuildingGood(IObjectBase *object) override;
    virtual Ptr<MapBuildingModificator> addMapBuildingModificator(IObjectBase *parent = nullptr) override;
    virtual void deleteMapBuildingModificator(IObjectBase *object) override;
    virtual Ptr<MapBuildingProjectile> addMapBuildingProjectile(IObjectBase *parent = nullptr) override;
    virtual void deleteMapBuildingProjectile(IObjectBase *object) override;
    virtual Ptr<MapBuildingWeapon> addMapBuildingWeapon(IObjectBase *parent = nullptr) override;
    virtual void deleteMapBuildingWeapon(IObjectBase *object) override;
    virtual Ptr<MapGood> addMapGood(IObjectBase *parent = nullptr) override;
    virtual void deleteMapGood(IObjectBase *object) override;
    virtual Ptr<MapObject> addMapObject(IObjectBase *parent = nullptr) override;
    virtual void deleteMapObject(IObjectBase *object) override;
    virtual Ptr<Mechanoid> addMechanoid() override;
    virtual void deleteMechanoid(IObjectBase *object) override;
    virtual Ptr<MechanoidQuest> addMechanoidQuest(IObjectBase *parent = nullptr) override;
    virtual void deleteMechanoidQuest(IObjectBase *object) override;
    virtual Ptr<Modification> addModification() override;
    virtual void deleteModification(IObjectBase *object) override;
    virtual Ptr<ModificationMap> addModificationMap(IObjectBase *parent = nullptr) override;
    virtual void deleteModificationMap(IObjectBase *object) override;
    virtual Ptr<Modificator> addModificator() override;
    virtual void deleteModificator(IObjectBase *object) override;
    virtual Ptr<Object> addObject() override;
    virtual void deleteObject(IObjectBase *object) override;
    virtual Ptr<Player> addPlayer() override;
    virtual void deletePlayer(IObjectBase *object) override;
    virtual Ptr<Projectile> addProjectile() override;
    virtual void deleteProjectile(IObjectBase *object) override;
    virtual Ptr<Quest> addQuest() override;
    virtual void deleteQuest(IObjectBase *object) override;
    virtual Ptr<QuestReward> addQuestReward(IObjectBase *parent = nullptr) override;
    virtual void deleteQuestReward(IObjectBase *object) override;
    virtual Ptr<QuestRewardEquipment> addQuestRewardEquipment(IObjectBase *parent = nullptr) override;
    virtual void deleteQuestRewardEquipment(IObjectBase *object) override;
    virtual Ptr<QuestRewardGlider> addQuestRewardGlider(IObjectBase *parent = nullptr) override;
    virtual void deleteQuestRewardGlider(IObjectBase *object) override;
    virtual Ptr<QuestRewardGood> addQuestRewardGood(IObjectBase *parent = nullptr) override;
    virtual void deleteQuestRewardGood(IObjectBase *object) override;
    virtual Ptr<QuestRewardModificator> addQuestRewardModificator(IObjectBase *parent = nullptr) override;
    virtual void deleteQuestRewardModificator(IObjectBase *object) override;
    virtual Ptr<QuestRewardProjectile> addQuestRewardProjectile(IObjectBase *parent = nullptr) override;
    virtual void deleteQuestRewardProjectile(IObjectBase *object) override;
    virtual Ptr<QuestRewardReputation> addQuestRewardReputation(IObjectBase *parent = nullptr) override;
    virtual void deleteQuestRewardReputation(IObjectBase *object) override;
    virtual Ptr<QuestRewardWeapon> addQuestRewardWeapon(IObjectBase *parent = nullptr) override;
    virtual void deleteQuestRewardWeapon(IObjectBase *object) override;
    virtual Ptr<ScriptVariable> addScriptVariable() override;
    virtual void deleteScriptVariable(IObjectBase *object) override;
    virtual Ptr<Setting> addSetting() override;
    virtual void deleteSetting(IObjectBase *object) override;
    virtual Ptr<String> addString() override;
    virtual void deleteString(IObjectBase *object) override;
    virtual Ptr<Table> addTable() override;
    virtual void deleteTable(IObjectBase *object) override;
    virtual Ptr<Weapon> addWeapon() override;
    virtual void deleteWeapon(IObjectBase *object) override;

    virtual Ptr<IObjectBase> addRecord(IObjectBase *parent = nullptr) override;
    virtual void deleteRecord(IObjectBase *data) override;

    virtual Ptr<TreeItem> printTree() const override;
    virtual Ptr<TreeItem> addRecord(TreeItem *item) override;
    virtual void deleteRecord(TreeItem *item) override;

    virtual OrderedObjectMap getOrderedMap(EObjectType type, std::function<bool(IObjectBase *)> f = std::function<bool(IObjectBase *)>()) const override;
};
