#include "token.h"

#include "print.h"

ModuleContext print(Tokens &tokens)
{
    ModuleContext mc;
    mc.hpp.addLine(autogenerated_warning);
    mc.hpp.addLine();
    mc.hpp.addLine(pragma_once);
    mc.hpp.addLine();
    mc.hpp.addLine("extern const Tokens tokens;");

    mc.cpp.addLine(autogenerated_warning);
    mc.cpp.addLine();
    mc.cpp.beginBlock("const Tokens tokens = ");
    for (auto &t : tokens)
        t.print(mc);
    mc.cpp.endBlock(true);
    return mc;
}
