/*
 * Polygon-4 Data Manager
 * Copyright (C) 2015-2016 lzwdgc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <Polygon4/DataManager/Schema/Token.h>

#include <Polygon4/DataManager/Common.h>
#include <Polygon4/DataManager/Schema/Print.h>

void Token::print(ModuleContext &mc)
{
    std::string s = "{ " + std::to_string(token) + ", ";
    switch (value.which())
    {
    case Integer:
        s += std::to_string(boost::get<int>(value));
        break;
    case Float:
        s += std::to_string(boost::get<double>(value));
        break;
    case String:
    {
        auto v = boost::get<std::string>(value);
        replace_all(v, "\n", " \\\n");
        s += "\"" + v + "\"";
        break;
    }
    default:
        break;
    }
    s += " },";
    mc.cpp.addLine(s);
}

ModuleContext print(Tokens &tokens)
{
    ModuleContext mc;
    mc.cpp.addLine(autogenerated_warning);
    mc.cpp.addLine();
    mc.cpp.beginBlock("const Tokens tokens = ");
    for (auto &t : tokens)
        t.print(mc);
    mc.cpp.endBlock(true);
    return mc;
}
