#include <Polygon4/DataManager/Schema/Token.h>

#include <Polygon4/DataManager/Common.h>
#include <Polygon4/DataManager/Schema/Print.h>

void Token::print(ModuleContext &mc)
{
    std::string s = "{ " + std::to_string(token) + ", ";
    switch (value.which())
    {
    case Integer:
        s += std::to_string(boost::get<int>(value));
        break;
    case Float:
        s += std::to_string(boost::get<double>(value));
        break;
    case String:
    {
        auto v = boost::get<std::string>(value);
        replace_all(v, "\n", " \\\n");
        s += "\"" + v + "\"";
        break;
    }
    default:
        break;
    }
    s += " },";
    mc.cpp.addLine(s);
}

ModuleContext print(Tokens &tokens)
{
    ModuleContext mc;
    mc.cpp.addLine(autogenerated_warning);
    mc.cpp.addLine();
    mc.cpp.beginBlock("const Tokens tokens = ");
    for (auto &t : tokens)
        t.print(mc);
    mc.cpp.endBlock(true);
    return mc;
}
